//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IOR", "FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LineDisplay.MachineGroup), "Machines", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LineDisplay.Machine), true)]
[assembly: EdmRelationshipAttribute("IOR", "FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LineDisplay.Machine), "Shifts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LineDisplay.Shift), true)]
[assembly: EdmRelationshipAttribute("IOR", "FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LineDisplay.Shift), "Sessions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LineDisplay.Session), true)]

#endregion

namespace LineDisplay
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IOREntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IOREntities object using the connection string found in the 'IOREntities' section of the application configuration file.
        /// </summary>
        public IOREntities() : base("name=IOREntities", "IOREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IOREntities object.
        /// </summary>
        public IOREntities(string connectionString) : base(connectionString, "IOREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IOREntities object.
        /// </summary>
        public IOREntities(EntityConnection connection) : base(connection, "IOREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MachineGroup> MachineGroups
        {
            get
            {
                if ((_MachineGroups == null))
                {
                    _MachineGroups = base.CreateObjectSet<MachineGroup>("MachineGroups");
                }
                return _MachineGroups;
            }
        }
        private ObjectSet<MachineGroup> _MachineGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MachineInput> MachineInputs
        {
            get
            {
                if ((_MachineInputs == null))
                {
                    _MachineInputs = base.CreateObjectSet<MachineInput>("MachineInputs");
                }
                return _MachineInputs;
            }
        }
        private ObjectSet<MachineInput> _MachineInputs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Machine> Machines
        {
            get
            {
                if ((_Machines == null))
                {
                    _Machines = base.CreateObjectSet<Machine>("Machines");
                }
                return _Machines;
            }
        }
        private ObjectSet<Machine> _Machines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shift> Shifts
        {
            get
            {
                if ((_Shifts == null))
                {
                    _Shifts = base.CreateObjectSet<Shift>("Shifts");
                }
                return _Shifts;
            }
        }
        private ObjectSet<Shift> _Shifts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MachineGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMachineGroups(MachineGroup machineGroup)
        {
            base.AddObject("MachineGroups", machineGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MachineInputs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMachineInputs(MachineInput machineInput)
        {
            base.AddObject("MachineInputs", machineInput);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Machines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMachines(Machine machine)
        {
            base.AddObject("Machines", machine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shifts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShifts(Shift shift)
        {
            base.AddObject("Shifts", shift);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IOR", Name="Machine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Machine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Machine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="machineGroupId">Initial value of the MachineGroupId property.</param>
        /// <param name="tOS">Initial value of the TOS property.</param>
        /// <param name="pulses">Initial value of the Pulses property.</param>
        /// <param name="pieces">Initial value of the Pieces property.</param>
        /// <param name="rmin">Initial value of the Rmin property.</param>
        /// <param name="rmax">Initial value of the Rmax property.</param>
        /// <param name="omin">Initial value of the Omin property.</param>
        /// <param name="omax">Initial value of the Omax property.</param>
        /// <param name="gmin">Initial value of the Gmin property.</param>
        /// <param name="gmax">Initial value of the Gmax property.</param>
        public static Machine CreateMachine(global::System.Int32 id, global::System.Int32 machineGroupId, global::System.Int32 tOS, global::System.Int32 pulses, global::System.Int32 pieces, global::System.Double rmin, global::System.Double rmax, global::System.Double omin, global::System.Double omax, global::System.Double gmin, global::System.Double gmax)
        {
            Machine machine = new Machine();
            machine.Id = id;
            machine.MachineGroupId = machineGroupId;
            machine.TOS = tOS;
            machine.Pulses = pulses;
            machine.Pieces = pieces;
            machine.Rmin = rmin;
            machine.Rmax = rmax;
            machine.Omin = omin;
            machine.Omax = omax;
            machine.Gmin = gmin;
            machine.Gmax = gmax;
            return machine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MachineGroupId
        {
            get
            {
                return _MachineGroupId;
            }
            set
            {
                OnMachineGroupIdChanging(value);
                ReportPropertyChanging("MachineGroupId");
                _MachineGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MachineGroupId");
                OnMachineGroupIdChanged();
            }
        }
        private global::System.Int32 _MachineGroupId;
        partial void OnMachineGroupIdChanging(global::System.Int32 value);
        partial void OnMachineGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TOS
        {
            get
            {
                return _TOS;
            }
            set
            {
                OnTOSChanging(value);
                ReportPropertyChanging("TOS");
                _TOS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TOS");
                OnTOSChanged();
            }
        }
        private global::System.Int32 _TOS;
        partial void OnTOSChanging(global::System.Int32 value);
        partial void OnTOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pulses
        {
            get
            {
                return _Pulses;
            }
            set
            {
                OnPulsesChanging(value);
                ReportPropertyChanging("Pulses");
                _Pulses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pulses");
                OnPulsesChanged();
            }
        }
        private global::System.Int32 _Pulses;
        partial void OnPulsesChanging(global::System.Int32 value);
        partial void OnPulsesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pieces
        {
            get
            {
                return _Pieces;
            }
            set
            {
                OnPiecesChanging(value);
                ReportPropertyChanging("Pieces");
                _Pieces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pieces");
                OnPiecesChanged();
            }
        }
        private global::System.Int32 _Pieces;
        partial void OnPiecesChanging(global::System.Int32 value);
        partial void OnPiecesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rmin
        {
            get
            {
                return _Rmin;
            }
            set
            {
                OnRminChanging(value);
                ReportPropertyChanging("Rmin");
                _Rmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rmin");
                OnRminChanged();
            }
        }
        private global::System.Double _Rmin;
        partial void OnRminChanging(global::System.Double value);
        partial void OnRminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rmax
        {
            get
            {
                return _Rmax;
            }
            set
            {
                OnRmaxChanging(value);
                ReportPropertyChanging("Rmax");
                _Rmax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rmax");
                OnRmaxChanged();
            }
        }
        private global::System.Double _Rmax;
        partial void OnRmaxChanging(global::System.Double value);
        partial void OnRmaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Omin
        {
            get
            {
                return _Omin;
            }
            set
            {
                OnOminChanging(value);
                ReportPropertyChanging("Omin");
                _Omin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Omin");
                OnOminChanged();
            }
        }
        private global::System.Double _Omin;
        partial void OnOminChanging(global::System.Double value);
        partial void OnOminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Omax
        {
            get
            {
                return _Omax;
            }
            set
            {
                OnOmaxChanging(value);
                ReportPropertyChanging("Omax");
                _Omax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Omax");
                OnOmaxChanged();
            }
        }
        private global::System.Double _Omax;
        partial void OnOmaxChanging(global::System.Double value);
        partial void OnOmaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Gmin
        {
            get
            {
                return _Gmin;
            }
            set
            {
                OnGminChanging(value);
                ReportPropertyChanging("Gmin");
                _Gmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gmin");
                OnGminChanged();
            }
        }
        private global::System.Double _Gmin;
        partial void OnGminChanging(global::System.Double value);
        partial void OnGminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Gmax
        {
            get
            {
                return _Gmax;
            }
            set
            {
                OnGmaxChanging(value);
                ReportPropertyChanging("Gmax");
                _Gmax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gmax");
                OnGmaxChanged();
            }
        }
        private global::System.Double _Gmax;
        partial void OnGmaxChanging(global::System.Double value);
        partial void OnGmaxChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups")]
        public MachineGroup MachineGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MachineGroup>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MachineGroup>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MachineGroup> MachineGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MachineGroup>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MachineGroup>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "MachineGroups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Shifts_dbo_Machines_Machine_Id", "Shifts")]
        public EntityCollection<Shift> Shifts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shift>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Shifts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shift>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Shifts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IOR", Name="MachineGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MachineGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MachineGroup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MachineGroup CreateMachineGroup(global::System.Int32 id)
        {
            MachineGroup machineGroup = new MachineGroup();
            machineGroup.Id = id;
            return machineGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "Machines")]
        public EntityCollection<Machine> Machines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Machine>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "Machines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Machine>("IOR.FK_dbo_Machines_dbo_MachineGroups_MachineGroupId", "Machines", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IOR", Name="MachineInput")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MachineInput : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MachineInput object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="machineId">Initial value of the MachineId property.</param>
        /// <param name="inputTimestamp">Initial value of the inputTimestamp property.</param>
        public static MachineInput CreateMachineInput(global::System.Int32 id, global::System.Int32 machineId, global::System.DateTime inputTimestamp)
        {
            MachineInput machineInput = new MachineInput();
            machineInput.Id = id;
            machineInput.MachineId = machineId;
            machineInput.inputTimestamp = inputTimestamp;
            return machineInput;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MachineId
        {
            get
            {
                return _MachineId;
            }
            set
            {
                OnMachineIdChanging(value);
                ReportPropertyChanging("MachineId");
                _MachineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MachineId");
                OnMachineIdChanged();
            }
        }
        private global::System.Int32 _MachineId;
        partial void OnMachineIdChanging(global::System.Int32 value);
        partial void OnMachineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime inputTimestamp
        {
            get
            {
                return _inputTimestamp;
            }
            set
            {
                OninputTimestampChanging(value);
                ReportPropertyChanging("inputTimestamp");
                _inputTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inputTimestamp");
                OninputTimestampChanged();
            }
        }
        private global::System.DateTime _inputTimestamp;
        partial void OninputTimestampChanging(global::System.DateTime value);
        partial void OninputTimestampChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IOR", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        public static Session CreateSession(global::System.Int32 id, global::System.DateTime start, global::System.DateTime end)
        {
            Session session = new Session();
            session.Id = id;
            session.Start = start;
            session.End = end;
            return session;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Shift_Id
        {
            get
            {
                return _Shift_Id;
            }
            set
            {
                OnShift_IdChanging(value);
                ReportPropertyChanging("Shift_Id");
                _Shift_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shift_Id");
                OnShift_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Shift_Id;
        partial void OnShift_IdChanging(Nullable<global::System.Int32> value);
        partial void OnShift_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts")]
        public Shift Shift
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shift> ShiftReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shift>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Shifts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IOR", Name="Shift")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shift : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shift object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        public static Shift CreateShift(global::System.Int32 id, global::System.DateTime start, global::System.DateTime end)
        {
            Shift shift = new Shift();
            shift.Id = id;
            shift.Start = start;
            shift.End = end;
            return shift;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Machine_Id
        {
            get
            {
                return _Machine_Id;
            }
            set
            {
                OnMachine_IdChanging(value);
                ReportPropertyChanging("Machine_Id");
                _Machine_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Machine_Id");
                OnMachine_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Machine_Id;
        partial void OnMachine_IdChanging(Nullable<global::System.Int32> value);
        partial void OnMachine_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines")]
        public Machine Machine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Machine> MachineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Machine>("IOR.FK_dbo_Shifts_dbo_Machines_Machine_Id", "Machines", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IOR", "FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Sessions")]
        public EntityCollection<Session> Sessions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Session>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Sessions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Session>("IOR.FK_dbo_Sessions_dbo_Shifts_Shift_Id", "Sessions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
